### ISSUE TITLE
Is this fix still valid?

### ISSUE THREAD

**Issue by berkersal** [OSS-App-Forks/vscode-oss-remotessh-fix#1]
I tried this fix but it fails while installing the vscode server on the server. I can provide logs if it is not reproducible.

**Comment by DroidFreak32** [comment]
I haven't been able to test it in a while.
Can you give the logs output?

**Comment by novirium** [comment]
On newer extension versions things have changed a little, but there is another method that doesn't involve editing any files directly - you can just remove the native node module that VSCode uses on the remote server to sign the Microsoft distribution (`vsda`), and if it can't load it, it doesn't use it to check any more.

Run on the server you're trying to connect to (changing the big long string of characters as necessary, it may differ):
```sh
rm ~/.vscode-server-oss/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node_modules/vsda/ -r
```

Close any existing connection attempts and wait for the vscode-server program to close on the remote server before retrying (or just reboot the server).

**Comment by DroidFreak32** [comment]
That actually worked!

**Comment by berkersal** [comment]
Sorry, I forgot to reply to your first response. After trying the new method it still doesn't work.

After deleting `.vscode-server-oss` and trying to connect the logs are like this:
```
[23:16:16.713] Log Level: 2
[23:16:16.715] SSH Resolver called for "ssh-remote+<SERVER NAME IN SSH CONFIG>", attempt 1
[23:16:16.715] "remote.SSH.useLocalServer": false
[23:16:16.716] "remote.SSH.showLoginTerminal": false
[23:16:16.716] "remote.SSH.remotePlatform": {"<SERVER NAME IN SSH CONFIG>":"linux"}
[23:16:16.716] "remote.SSH.path": undefined
[23:16:16.717] "remote.SSH.configFile": undefined
[23:16:16.717] "remote.SSH.useFlock": true
[23:16:16.717] "remote.SSH.lockfilesInTmp": false
[23:16:16.718] "remote.SSH.localServerDownload": auto
[23:16:16.718] "remote.SSH.remoteServerListenOnSocket": false
[23:16:16.718] "remote.SSH.showLoginTerminal": false
[23:16:16.719] "remote.SSH.defaultExtensions": []
[23:16:16.719] "remote.SSH.loglevel": 2
[23:16:16.719] "remote.SSH.enableDynamicForwarding": true
[23:16:16.719] "remote.SSH.enableRemoteCommand": false
[23:16:16.720] "remote.SSH.serverPickPortsFromRange": {}
[23:16:16.720] "remote.SSH.serverInstallPath": {}
[23:16:16.723] VS Code version: 1.76.1
[23:16:16.723] Remote-SSH version: remote-ssh@0.98.0
[23:16:16.723] linux x64
[23:16:16.725] SSH Resolver called for host: <SERVER NAME IN SSH CONFIG>
[23:16:16.725] Setting up SSH remote "<SERVER NAME IN SSH CONFIG>"
[23:16:16.729] Using commit id "5e805b79fcb6ba4c2d23712967df89a089da575b" and quality "stable" for server
[23:16:16.734] Install and start server if needed
[23:16:16.738] PATH: <MY PATH ON CLIENT COMPUTER>
[23:16:16.738] Checking ssh with "ssh -V"
[23:16:16.748] > OpenSSH_9.2p1, OpenSSL 3.0.8 7 Feb 2023

[23:16:16.755] Running script with connection command: ssh -T -D 45665 -o ConnectTimeout=15 '<SERVER NAME IN SSH CONFIG>' bash
[23:16:17.969] > 2313137a51ab: running
[23:16:17.969] Got some output, clearing connection timeout
[23:16:18.014] > Acquiring lock on /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/vscode-remote-lock.root.5e805b79fcb6ba4c2d23712967df89a089da575b
[23:16:18.026] > Installing to /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b...
> 2313137a51ab%%1%%
[23:16:18.032] > Downloading with wget
[23:16:23.885] > Download complete
[23:16:23.891] > 2313137a51ab%%2%%
> tar --version:
> tar (GNU tar) 1.26
> Copyright (C) 2011 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
>
> Written by John Gilmore and Jay Fenlason.
[23:16:26.700] > ERROR: /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/node or /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/bin/code-server-oss don't exist
> Trigger local server download
> 2313137a51ab:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/root/.vscode-server-oss/bin/==
> destFolder2==5e805b79fcb6ba4c2d23712967df89a089da575b==
> 2313137a51ab:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/vscode-scp-done.flag and vscode-server.tar.gz to exist
>
[23:16:26.700] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b"}
[23:16:26.701] Downloading VS Code server locally...
[23:16:32.741] Downloaded VS Code server to /tmp/19339fcd-d022-413d-ab5d-445e828336cc
[23:16:32.741] Renamed VS Code server to /tmp/vscode_server_1678824992741/vscode-server.tar.gz
[23:16:32.744] PATH: <MY PATH ON CLIENT COMPUTER>
[23:16:32.744] Checking ssh with "ssh -V"
[23:16:32.763] > OpenSSH_9.2p1, OpenSSL 3.0.8 7 Feb 2023

[23:16:32.764] Testing scp with "scp"
[23:16:32.769] scp exited with code: 1
[23:16:32.769] Got stderr from scp: usage: scp [-346ABCOpqRrsTv] [-c cipher] [-D sftp_server_path] [-F ssh_config]
           [-i identity_file] [-J destination] [-l limit] [-o ssh_option]
           [-P port] [-S program] [-X sftp_option] source ... target
[23:16:32.770] Copying file to remote with scp -o ConnectTimeout=15 'vscode-server.tar.gz' 'vscode-scp-done.flag' '<SERVER NAME IN SSH CONFIG>':'/root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b'
[23:16:32.771] Using cwd: file:///tmp/vscode_server_1678824992741
[23:16:33.852] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA
<DOWNLOAD STUFF>
[23:17:46.496] > vscode-server.tar.gz                          100%   63MB 885.3KB/s   01:12
[23:17:46.695] > vscode-scp-done.flag                            0%    0     0.0KB/s   --:-- ETA
[23:17:46.745] > vscode-scp-done.flag                          100%    9     0.2KB/s   00:00
[23:17:47.374] "Copy server to host" terminal command done
[23:17:47.737] > Found flag and server on host
> 2313137a51ab%%2%%
> tar --version:
> tar (GNU tar) 1.26
> Copyright (C) 2011 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
>
> Written by John Gilmore and Jay Fenlason.
[23:17:50.595] > mv: cannot move 'vscode-server-linux-x64/bin' to './bin': Directory not empty
> mv: cannot move 'vscode-server-linux-x64/extensions' to './extensions': Directory not empty
[23:17:50.643] >
[23:17:50.669] > mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Directory not empty
> mv: cannot move 'vscode-server-linux-x64/out' to './out': Directory not empty
[23:17:50.693] > ERROR: /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/node or /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/bin/code-server-oss don't exist
> Already attempted local download, failing
> 2313137a51ab: start
> exitCode==37==
> listeningOn====
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/0==
> platform==linux==
> unpackResult==missingFiles==
> didLocalDownload==1==
> downloadTime==5856==
> installTime==2850==
> extInstallTime====
> serverStartTime====
> 2313137a51ab: end
>
[23:17:50.693] Received install output:
exitCode==37==
listeningOn====
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/0==
platform==linux==
unpackResult==missingFiles==
didLocalDownload==1==
downloadTime==5856==
installTime==2850==
extInstallTime====
serverStartTime====

[23:17:50.696] Resolver error: Error: Failed to install the VS Code Server
	at m.ServerInstallError (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:584322)
	at f (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:578617)
	at t.handleInstallOutput (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:581404)
	at t.tryInstall (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:681793)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:644041
	at async t.withShowDetailsEvent (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:647359)
	at async t.resolve (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:645091)
	at async /home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:720839
[23:17:50.701] ------




[23:17:51.427] "install" terminal command done
[23:17:51.427] Install terminal quit with output:
```

After this, I apply the new fix and the logs are like this:
```
[23:27:03.630] Log Level: 2
[23:27:03.634] SSH Resolver called for "ssh-remote+<SERVER NAME IN SSH CONFIG>", attempt 1
[23:27:03.635] "remote.SSH.useLocalServer": false
[23:27:03.637] "remote.SSH.showLoginTerminal": false
[23:27:03.639] "remote.SSH.remotePlatform": {"<SERVER NAME IN SSH CONFIG>":"linux"}
[23:27:03.639] "remote.SSH.path": undefined
[23:27:03.641] "remote.SSH.configFile": undefined
[23:27:03.642] "remote.SSH.useFlock": true
[23:27:03.643] "remote.SSH.lockfilesInTmp": false
[23:27:03.644] "remote.SSH.localServerDownload": auto
[23:27:03.644] "remote.SSH.remoteServerListenOnSocket": false
[23:27:03.645] "remote.SSH.showLoginTerminal": false
[23:27:03.645] "remote.SSH.defaultExtensions": []
[23:27:03.646] "remote.SSH.loglevel": 2
[23:27:03.646] "remote.SSH.enableDynamicForwarding": true
[23:27:03.647] "remote.SSH.enableRemoteCommand": false
[23:27:03.647] "remote.SSH.serverPickPortsFromRange": {}
[23:27:03.647] "remote.SSH.serverInstallPath": {}
[23:27:03.660] VS Code version: 1.76.1
[23:27:03.660] Remote-SSH version: remote-ssh@0.98.0
[23:27:03.660] linux x64
[23:27:03.662] SSH Resolver called for host: <SERVER NAME IN SSH CONFIG>
[23:27:03.662] Setting up SSH remote "<SERVER NAME IN SSH CONFIG>"
[23:27:03.667] Using commit id "5e805b79fcb6ba4c2d23712967df89a089da575b" and quality "stable" for server
[23:27:03.673] Install and start server if needed
[23:27:03.678] PATH: <MY PATH ON CLIENT COMPUTER>
[23:27:03.678] Checking ssh with "ssh -V"
[23:27:03.693] > OpenSSH_9.2p1, OpenSSL 3.0.8 7 Feb 2023

[23:27:03.697] Running script with connection command: ssh -T -D 40633 -o ConnectTimeout=15 '<SERVER NAME IN SSH CONFIG>' bash
[23:27:05.014] > 294efa3860d8: running
[23:27:05.015] Got some output, clearing connection timeout
[23:27:05.050] > Acquiring lock on /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/vscode-remote-lock.root.5e805b79fcb6ba4c2d23712967df89a089da575b
[23:27:05.077] > Installing to /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b...
> 294efa3860d8%%1%%
[23:27:05.099] > Downloading with wget
[23:27:10.853] > Download complete
> 294efa3860d8%%2%%
> tar --version:
[23:27:10.899] > tar (GNU tar) 1.26
> Copyright (C) 2011 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
>
> Written by John Gilmore and Jay Fenlason.
[23:27:13.615] > mv: cannot move 'vscode-server-linux-x64/bin' to './bin': Directory not empty
[23:27:13.696] > mv: cannot move 'vscode-server-linux-x64/extensions' to './extensions': Directory not empty
[23:27:13.757] > mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Directory not empty
> mv: cannot move 'vscode-server-linux-x64/out' to './out': Directory not empty
[23:27:13.786] > ERROR: /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/node or /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/bin/code-server-oss don't exist
> Trigger local server download
> 294efa3860d8:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/root/.vscode-server-oss/bin/==
> destFolder2==5e805b79fcb6ba4c2d23712967df89a089da575b==
> 294efa3860d8:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/vscode-scp-done.flag and vscode-server.tar.gz to exist
>
[23:27:13.787] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b"}
[23:27:13.787] Downloading VS Code server locally...
[23:27:19.976] Downloaded VS Code server to /tmp/ffd0f4c5-281f-471f-8ccd-cb19e5fd4cbc
[23:27:19.977] Renamed VS Code server to /tmp/vscode_server_1678825639976/vscode-server.tar.gz
[23:27:19.979] PATH: <MY PATH ON CLIENT COMPUTER>
[23:27:19.979] Checking ssh with "ssh -V"
[23:27:19.991] > OpenSSH_9.2p1, OpenSSL 3.0.8 7 Feb 2023

[23:27:19.991] Testing scp with "scp"
[23:27:19.997] scp exited with code: 1
[23:27:19.997] Got stderr from scp: usage: scp [-346ABCOpqRrsTv] [-c cipher] [-D sftp_server_path] [-F ssh_config]
           [-i identity_file] [-J destination] [-l limit] [-o ssh_option]
           [-P port] [-S program] [-X sftp_option] source ... target
[23:27:19.999] Copying file to remote with scp -o ConnectTimeout=15 'vscode-server.tar.gz' 'vscode-scp-done.flag' '<SERVER NAME IN SSH CONFIG>':'/root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b'
[23:27:19.999] Using cwd: file:///tmp/vscode_server_1678825639976
[23:27:21.089] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA
<DOWNLOAD STUFF>
[23:28:30.577] > vscode-server.tar.gz                          100%   63MB 925.5KB/s   01:09
[23:28:30.773] > vscode-scp-done.flag                            0%    0     0.0KB/s   --:-- ETA
[23:28:30.821] > vscode-scp-done.flag                          100%    9     0.2KB/s   00:00
[23:28:31.457] "Copy server to host" terminal command done
[23:28:31.883] > Found flag and server on host
> 294efa3860d8%%2%%
> tar --version:
> tar (GNU tar) 1.26
> Copyright (C) 2011 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
>
> Written by John Gilmore and Jay Fenlason.
[23:28:34.560] > mv: cannot move 'vscode-server-linux-x64/bin' to './bin': Directory not empty
> mv: cannot move 'vscode-server-linux-x64/extensions' to './extensions': Directory not empty
[23:28:34.614] > mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Directory not empty
> mv: cannot move 'vscode-server-linux-x64/out' to './out': Directory not empty
> ERROR: /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/node or /root/.vscode-server-oss/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/bin/code-server-oss don't exist
> Already attempted local download, failing
> 294efa3860d8: start
> exitCode==37==
> listeningOn====
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/0==
> platform==linux==
> unpackResult==missingFiles==
> didLocalDownload==1==
> downloadTime==5774==
> installTime==2677==
> extInstallTime====
> serverStartTime====
> 294efa3860d8: end
[23:28:34.614] Received install output:
exitCode==37==
listeningOn====
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/0==
platform==linux==
unpackResult==missingFiles==
didLocalDownload==1==
downloadTime==5774==
installTime==2677==
extInstallTime====
serverStartTime====

[23:28:34.617] Resolver error: Error: Failed to install the VS Code Server
	at m.ServerInstallError (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:584322)
	at f (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:578617)
	at t.handleInstallOutput (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:581404)
	at t.tryInstall (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:681793)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:644041
	at async t.withShowDetailsEvent (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:647359)
	at async t.resolve (/home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:645091)
	at async /home/berkersal/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:720839
[23:28:34.624] ------




[23:28:35.310] "install" terminal command done
[23:28:35.310] Install terminal quit with output:

```

**Comment by DroidFreak32** [comment]
[berkersal](https://github.com/berkersal) Is "serverApplicationName" in your PC's product.json set to code-server?

```bash
❯ grep "serverApplicationName" /usr/lib/code/product.json
 "serverApplicationName": "code-server",
```

**Comment by berkersal** [comment]
I thought I did not need that for the new fix. Let me do that again

Edit: It worked 🎉. Modifying ServerApplicationName and deleting `vsda` are the only needed things
